apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: 8080
    targetPort: 80
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ .Values.appName }}
    tier: frontend
  type: NodePort