apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ .Values.appName }}
    tier: frontend