apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 3100
  selector:
    app: {{ .Values.appName }}
    tier: frontend
  type: NodePort